services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  EliasHaeussler\Typo3Warming\:
    resource: '../Classes/*'

  EliasHaeussler\Typo3Warming\Backend\ToolbarItems\CacheWarmupToolbarItem:
    public: true
  EliasHaeussler\Typo3Warming\Cache\CacheManager:
    arguments:
      $cache: '@cache.core'
  EliasHaeussler\Typo3Warming\Configuration\Configuration:
    public: true
  EliasHaeussler\Typo3Warming\Controller\CacheWarmupController:
    public: true
  EliasHaeussler\Typo3Warming\Sitemap\SitemapLocator:
    public: true
    arguments:
      $providers:
        - '@EliasHaeussler\Typo3Warming\Sitemap\Provider\SiteProvider'
        - '@EliasHaeussler\Typo3Warming\Sitemap\Provider\RobotsTxtProvider'
        - '@EliasHaeussler\Typo3Warming\Sitemap\Provider\DefaultProvider'

  EliasHaeussler\Typo3Warming\Command\ShowUserAgentCommand:
    tags:
      - name: console.command
        command: warming:showuseragent
        schedulable: false
  EliasHaeussler\Typo3Warming\Command\WarmupCommand:
    tags:
      - name: console.command
        command: warming:cachewarmup

  cache.core:
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['core']
