services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  EliasHaeussler\Typo3Warming\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/{Model,Type}/*'
      - '../Classes/Enums/*'
      - '../Classes/Event/*'
      - '../Classes/Exception/*'
      - '../Classes/Http/Message/Event/*'
      - '../Classes/Http/Message/Handler/*'
      - '../Classes/Log/*'
      - '../Classes/Result/*'
      - '../Classes/ValueObject/*'

  EliasHaeussler\Typo3Warming\Command\ShowUserAgentCommand:
    tags:
      - name: console.command
        command: warming:showuseragent
        description: 'Show custom "User-Agent" header to be used for Frontend requests by default crawlers.'
        schedulable: false

  CuyZ\Valinor\Mapper\TreeMapper:
    factory: ['@EliasHaeussler\Typo3Warming\Mapper\MapperFactory', 'get']

  # Default crawling strategies
  EliasHaeussler\CacheWarmup\Crawler\Strategy\SortByChangeFrequencyStrategy:
  EliasHaeussler\CacheWarmup\Crawler\Strategy\SortByLastModificationDateStrategy:
  EliasHaeussler\CacheWarmup\Crawler\Strategy\SortByPriorityStrategy:
